theme = "kanagawa-dragon"

[editor]
bufferline = "multiple"
line-number = "relative"
rulers = [120]
true-color = true
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
# Default yank -> primary selection (X11 PRIMARY / Wayland primary)
y = ":clipboard-yank"

# Paste from primary selection
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"

[keys.select]
# Default yank -> primary selection (X11 PRIMARY / Wayland primary)
y = ":clipboard-yank"

# Paste from primary selection
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
